name: Test latest Gradle
on:
  schedule:
    - cron: 0 0 * * 0 # weekly
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          cache-read-only: false

      - run: | # just test build configuration
          gradle build --dry-run 
